### ISSUE TITLE
Support Node.js and add to NPM

### ISSUE THREAD

**Issue by erhhung** [epistemex/pngtoy#4]
It would be nice to add support for using this package from Node.js by installing it using npm.

Instead of having `pngtoy.fetch(url)`, which is currently based on a browser's `XMLHttpRequest`, offer a generic `pngtoy.decode(buf, opts)` where `buf` is either a `Buffer` (Node.js) or a `Uint8Array` (browser) (the current `decode()` does not accept a byte buffer of any kind).

Then you can have optional convenience methods `pngtoy.loadFromUrl(url)` and `pngtoy.loadFromFile(path)` that delegate to the `decode()` method.

Dependencies such as `XMLHttpRequest` and `Canvas` can be polyfilled in Node.js and only included in `package.json` instead of `bower.json`. This way the complicated core PNG parsing logic can be used on the frontend as well as on the backend.

**Comment by epistemex** [comment]
This can be a nice workaround/solution to get node support. Thanks again @erhhung !

**Comment by epistemex** [comment]
`fetch()` can now take ArrayBuffer or typed array view as argument in addition to URL types. There is partial node.js support (very rough and untested) but won't be added to NPM before in beta.

It won't use Buffer (with node.js) as that would require some rewriting, but it should not be a big issue since the main difference is buffer initialization (zeros the buffer with ArrayBuffer) unless you need a huge volume of files/users.
