### ISSUE TITLE
16-bit grayscale values have wrong endianness

### ISSUE THREAD

**Issue by erhhung** [epistemex/pngtoy#5]
I believe there is a bug with how 16-bit grayscale values are decoded, that the byte-order should be reversed.

After calling `pngtoy.fetch()` and `pngtoy.decode()`, `bmp.depth` = 16 while the `bmp.bitmap` Uint16Array contains unusually large values for a "dark" bitmap. With the following image, once I manually swapped the upper and lower bytes, the gradient looks correct.

__16-bit depth map PNG:__ [sample-depth.png](https://cloud.githubusercontent.com/assets/5808864/18565316/33f81ee0-7b44-11e6-968e-c0fcb05985b3.png)
__Corresponding RGB:__ [sample-color.jpg](https://cloud.githubusercontent.com/assets/5808864/18565361/55d57256-7b44-11e6-97b3-4ba1322eb24a.jpg)

The grayscale image is quite dark, so as an image you may not see much unless you normalize it into RGBA for display. See my [`depthmap-loader.js`](https://gist.github.com/erhhung/766766d761f1ef0b807e275fc8ed70f9) for an example of using PngToy to load the sample PNG and applying the workaround.

**Comment by epistemex** [comment]
Thanks erhhung, I will check it out. Note that the png format is big-endian and if you use the raw unfiltered buffer (but not the rgba converter) the bytes need to swapped manually. But I will check out your sample images and code and see what steps are there. I will provide a fix for pngtoy if the bytes are swapped. Thanks again.

**Comment by erhhung** [comment]
I should have included a visual comparison. The top is the normalized version of the that PNG, and the bottom is without swapping the bytes. I'm not sure how the file was initially written, but in Photoshop it loads correctly (dark but correct gradient). In the browser the image seems to load correctly, but obviously losing most of the smooth gradations.

![fixed-vs-unfixed](https://cloud.githubusercontent.com/assets/5808864/18567605/cf9cb4d8-7b4d-11e6-822c-40b4a70436a8.png)

**Comment by epistemex** [comment]
It's for sure a byte-order problem, but it's not really an issue with PngToy per-se. The raw, but filtered buffer decoded by `decode()` is in its original byte-order format (big-endian) as per the standard. The only thing `decode()` does is to _unfilter_ each scan-line. Which of course mean the byte-order will still remain in big-endian and has to be swapped manually as a post-step to this. This is so because the intent with PngToy is to work directly with the low-level raw buffer data of the file, at least at this stage.

You can see the correct byte-order is being produced if all the process steps are followed through to target canvas or a browser compatible bitmap by using `convertToCanvas()` or `convertToRGBA()`. See the PngImage.js for an example of this step.

Optionally, you could consider using the DataView (`view` property) on the PngToy object to read each Uint16 value (you would need the IDAT chunk to get the offset and length though). This way you can have the browser swap the byte-order using the little-endian flag. I'm not sure (and I doubt) it will be faster than what you're already doing though using shift+or operations.

(Not directly related but meant tip as to the darkness in the original image: you may be able to avoid the normalization step by a simple gamma correction step to the produced byte buffer. There is a function `getGammaLUT()` on the main object which allows you to produce a look-up table. This will lift the mid-tones. A standard gamma value of 2.2-2.4 seem to do the trick. Just pass through each gray-scale byte (`newByte = lut(oldByte); // [0,255]`) to convert. Optionally embed a gAMA chunk in the PNG (or override its value in the chunk before processing).):
